version: '3'

services:
  
  frontend-service:
    tty: true
    build: ./materialfrontend
    ports:
     - 8081:8081
    depends_on:
     - backend-service
    container_name: frontend
 
  backend-service: 
    tty: true
    build: ./materialfinder3

    environment:
    # Diese IP-Adresse ERSETZEN! Den Rest der Zeile unverändert lassen
      - DJANGO_ALLOWED_HOSTS=localhost 83.229.85.34 backend-service

    
