# Generated by Django 4.1.5 on 2023-02-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materialapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kunststoffe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "materialapp_kunststoffe",
                "managed": False,
            },
        ),
    ]
