# Generated by Django 4.1.5 on 2023-02-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materialapp", "0002_kunststoffe"),
    ]

    operations = [
        migrations.AddField(
            model_name="kunststoffe",
            name="abrieb_bestaendig",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="biokompatibel",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="bruchfest",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="chemisch_bestaendig",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="dichte",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=-1, max_digits=5
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="elastisch",
            field=models.TextField(
                choices=[
                    ("nein", "nein"),
                    ("etwas", "etwas"),
                    ("normal", "normal"),
                    ("hoch", "hoch"),
                    ("sehr hoch", "sehr hoch"),
                ],
                default="nein",
            ),
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="entflammbar",
            field=models.TextField(
                choices=[
                    ("nein", "nein"),
                    ("schwer", "schwer"),
                    ("feuerbestaendig", "feuerbestaendig"),
                ],
                default="nein",
            ),
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="fachbezeichnung",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="festigkeit",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="feuchtigkeits_bestaendig",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="firmeneigen",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="glasuebergangstemp",
            field=models.IntegerField(blank=True, default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="haerte",
            field=models.IntegerField(blank=True, default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="handelsname",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="korrosion_bestaendig",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="kosten",
            field=models.TextField(
                choices=[
                    ("normal", "normal"),
                    ("hoch", "hoch"),
                    ("niedrig", "niedrig"),
                ],
                default="normal",
            ),
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="langlebig",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="lebensmittelecht",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="nachbearbeitung",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="nachteile",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="name",
            field=models.CharField(default="default", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="oele_bestaendig",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="sterilisierbar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="temp_kalt",
            field=models.IntegerField(blank=True, default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="temperaturbestaendig",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="transparent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="umweltvertraeglich",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="uvbestaendig",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="verfahren",
            field=models.TextField(
                blank=True,
                choices=[
                    ("FDM", "FDM"),
                    ("FFF", "FFF"),
                    ("SLS", "SLS"),
                    ("POLYJET", "Polyjet"),
                    ("SLA", "SLA"),
                    ("DLS", "DLS"),
                    ("DLP", "DLP"),
                ],
            ),
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="verwendung",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="vorteile",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="waermeformbestaendigkeit",
            field=models.IntegerField(blank=True, default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="wandstaerke",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=-1, max_digits=5
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kunststoffe",
            name="witterungsbestaendig",
            field=models.BooleanField(default=False),
        ),
    ]
