# Generated by Django 4.1.5 on 2023-02-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materialapp", "0003_kunststoffe_abrieb_bestaendig_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kunststoffe",
            name="dichte",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=-1, max_digits=5
            ),
        ),
    ]
